version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14.5
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "pdd-db"
      POSTGRES_USER: "pdd-user"
      POSTGRES_PASSWORD: "pgpwd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
#      - ../2. Init Database:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pdd-user -d pdd-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  redis:
    image: redis:7.2-rc2
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass qwerty12345678
    ports:
      - '6379:6379'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
#    ipam:
#      driver: bridge
#      config:
#        - subnet: 172.77.1.0/26



