spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/pdd-db
    username: pdd-user
    password: pgpwd

  jpa:
    show-sql: false
    generate-ddl: false

telegram:
  bot-name: "@ppdcheck_testbot"

  session:
    timeout: 1800                 # Время жизни сессии (в секундах)
    redis:
      flush-mode: on_save         # Указываем, когда изменения сеанса записываются в хранилище (immediate или on_save)
      namespace: ppdcheck:session    # Пространство имен для ключей, используемых для хранения сессий.
      save-mode: on_set_attribute # Определяет в какой момент происходит сохранение изменений сессии (on_set_attribute, on_get_attribute, always)
    data:
      redis: # Настраиваем подключение к Redis
        client-type: lettuce        # Указываем тип клиента Redis (jedis или lettuce)
        database: 0                 # Указываем номер БД Redis
        host: localhost             # Хост подключения
        port: 6379                  # Порт подключения
        password: qwerty12345678    # Пароль подключения
        lettuce: # Настраиваем пул подключений клиента lettuce
          pool:
            max-active: 16          # Максимальное количество подключений в пуле
            max-idle: 8             # Минимальное количество "idle" подключений в пуле